---

# Example config file for door_access

global:
  log_level: "INFO"
  url: "http://example.com:8000/api/v0/tags/verify_tag/"

readers:
  - name: "Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader"
