---

# Example config file for door_access

global:
  log_level: "INFO"
  url: "https://127.0.0.1/api/v0/tags/verify_tag/"

api:
  auth_scheme: "Token"
  token: "Add-your-API-Token"

readers:
  - name: "Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader"
